### PR TITLE
Release - v5.3.0

### LINKED ISSUE #276: Override key mapping after app is launched
Hello,
is it possible to setup the key mapping **after** the app is launched? Reading the lightning sdk, it seems the keys register can happen only inside the Application class' constructor, no way to invoke this with a public method.

### LINKED ISSUE #350: Allow optional parameters to be specified in the Lightning Router path
As of now with the latest SDK, there is no option in router path to specify optional parameters.

For example: if I want to make the playlistId, an optional field in the below path, it would not be possible.
{
  path: 'player/:assetId/:playlistId',
  component: Player
}

I would either need to specify two different routes to the same component.

It would be very helpful to have a way to specify optional fields in router path with a '?' suffix for the optional params.

example:
{
  path: 'player/:assetId/:playlistId?',
  component: Player
}

would route to

http://some/url#player/1
http://some.url#player/1/2

### LINKED ISSUE #359: App version wrongly positioned
Hi Lightning SDK team,

Since Lightning SDK 5.2.0, the app version is wrongly position for apps that are set to run in 1280x720 (0.6667 precision). See here a screenshot:

image

**Steps to reproduce:**
1. Create a new Lightning app with the CLI (`lng create`)
2. Add the following `stage` settings to the `setting.json` file:
```
"w": 1280,
"h": 720,
"precision": 0.66667
```

**Expected behaviour:**
The app version's blue rectangle should be positioned in the bottom right corner, as it has been in previous Lightning SDK versions.

**Observed behaviour:**
The app version's blue rectangle positioning is not correct.

**Happens since:** 5.2.0

### LINKED ISSUE #360: ENH: Allow plugins to load local json files
On certain plugins, such as the `Language` plugin, when deployed to devices that use the `file:///` protocol, if we ship our App with a local translation file, it fails on some older platforms when using the `fetch` API polyfill.

For example, on Tizen 3.0 that has the Chromium version 39, it uses the `fetch` API polyfill and fails to load the translations file causing our App to stay on a black screen.
However, on Tizen 5.5 that has the Chromium version 69 and doesn't need to polyfill the `fetch` API, it loads with no issue.

I'll provide a PR for you to take a look at and merge if it seems good to you.

### LINKED ISSUE #365: Router: using on provider changes the app state to the page instead of maintaining on the previous
Hello,

We were implementing a menu as a widget and came across a weird bug when using the `on` data provider on a route.
Each menu item does a `Router.navigate('path')` and, when we use the `on` data provider the focus would be stolen by the page instead of maintaining the focus on the page.

After some digging, I found the culript.

Here, it is setting and exporting a `previousState` variable:

https://github.com/rdkcentral/Lightning-SDK/blob/82b8948ca0e7efe7afe5a94ba5700d21a9cc880c/src/Router/utils/provider.js#L25-L32

Here, it is using a local variable with public get/set:

https://github.com/rdkcentral/Lightning-SDK/blob/eeb784375fa28e66286411997609d3302af4e97e/src/Router/utils/router.js#L147-L152
https://github.com/rdkcentral/Lightning-SDK/blob/eeb784375fa28e66286411997609d3302af4e97e/src/Router/utils/router.js#L439-L445

However, the setter method is never called because the `provider.js` file is using a different variable instead of the setter.

https://github.com/rdkcentral/Lightning-SDK/blob/2b0d10e6d36ae9d855d8f0ac29e8eaccae807ebf/src/Router/utils/loader.js#L53-L61

I'll provide a PR to fix this issue.

### LINKED ISSUE #375: Backtracking docs with no matching code
Under deeplinking - there is a backtracking flag
https://rdkcentral.github.io/Lightning-SDK/#/plugins/router/deeplinking?id=backtracking

However, there is no actual code based on that flag. So either something needs adding to the code or the docs need removing.

https://forum.lightningjs.io/t/backtracking-is-not-working-deeplinking/573

### PR DESCRIPTION
**Pull request by uguraslan**
## Changes

**Merged**

- Fixed #360 with [PR #361 and PR #370]
- Fixed #365 with [PR #366]
- Fixed #359 with [PR #368]
- Updated `@metrological/sdk` and `localCookie` NPM package paths with [PR #369]
- Fixed #350 with [PR #362]
- Added Subtitles plugin for displaying subtitles (closed captions) with [PR #353]
- Fixed #276 with [PR #364]
- Fixed #375 with [PR #376]

## To-do

- [x] Update `CHANGELOG.md`
- [x] Update `docs/changelog.md`

### CODE REVIEW

**Comment by uguraslan** [comment]
All PRs have been merged into the release branch of v5.3.0. This PR is ready for the final review before the release.

File: src/Application/index.js [hunk 1]
```diff
@@ -119,6 +119,32 @@ export default function(App, appData, platformSettings) {
...
+    get keymapping() {
+      return this.stage.application.config.keys
+    }
+
+    /**
+     * This function overides the default keymap with the latest keymap.
+     * @param customKeymap
+     * @param keepDuplicates
+     */
+    overRideKeyMap(customKeymap, keepDuplicates = false) {
```
Comment (ricardo-a-alves-alb) [inline src/Application/index.js:131]: Why is the word override capitalized like this?

File: src/Subtitles/SubtitleComponent.js [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+    return {
+      visible: false,
+      rect: true,
+      color: 0x90000000,
+      shader: { type: Lightning.shaders.RoundedRectangle, radius: 5 },
+      Text: {
+        y: 5,
+        x: 20,
+        text: {
+          fontColor: 0xffffffff,
```
Comment (ricardo-a-alves-alb) [inline src/Subtitles/SubtitleComponent.js:33]: This doesn't seem correct. Isn't the property `textColor`? [Related docs](https://github.com/rdkcentral/Lightning/blob/master/docs/RenderEngine/Textures/Text.md)

**Review by ricardo-a-alves-alb — CHANGES_REQUESTED** [review]
Also, why was `static/fonts/Roboto-Regular.ttf` added?

**Comment by sandeep-vedam** [comment]
> Also, why was `static/fonts/Roboto-Regular.ttf` added?

Thanks for noticing and highlighting this. @ricardo-a-alves-alb 

This was added at commit 56b8b93. The font was used in Subtitle plugin at the initial stages of development. Now there is no use for it as the feature is matured enough to use. We will remove this.

File: src/Application/index.js (hunk 1 above)
Comment (uguraslan) [reply src/Application/index.js]: Thanks @ricardo-a-alves-alb for pointing out that, we have updated the function name as well as some variables names to make it all consistent.

File: src/Subtitles/SubtitleComponent.js (hunk 2 above)
Comment (uguraslan) [reply src/Subtitles/SubtitleComponent.js]: Thanks, this also has been fixed.

File: src/Subtitles/SubtitleComponent.js [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+    const textTag = this.tag('Text').text
+    return {
+      fontFace: textTag.fontFace || 'sans-serif',
+      fontSize: textTag.fontSize,
+      lineHeight: textTag.lineHeight,
+      textAlign: textTag.textAlign,
+      wordWrap: true,
+      maxLines: textTag.maxLines,
+    }
+  }
```
Comment (ricardo-a-alves-alb) [inline src/Subtitles/SubtitleComponent.js:66]: Should the textColor be also returned here?

File: src/Subtitles/SubtitleComponent.js [hunk 4]
```diff
@@ -0,0 +1,203 @@
...
+
+  set fontSize(v) {
+    this.tag('Text').text.fontSize = v
+    this.tag('Text').text.lineHeight = v * 1.3
+  }
+
+  set fontColor(v) {
+    this.tag('Text').color = v
+  }
```
Comment (ricardo-a-alves-alb) [inline src/Subtitles/SubtitleComponent.js:150]: Should this also be renamed to textColor? And it should also patch the textColor, not the color property of the Texture.

File: src/Subtitles/SubtitleComponent.js [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+
+  _init() {
+    this._textTextureDefaults = new Lightning.textures.TextTexture(this.stage).cloneArgs()
+
+    this.tag('Text').on('txLoaded', ({ _source }) => {
+      this.w = _source.w + this.tag('Text').x * 2
+      this.h = _source.h
+      this.position()
+    })
```
Comment (ricardo-a-alves-alb) [inline src/Subtitles/SubtitleComponent.js:53]: Probably should add a TODO to fix this when this PR gets pushed to the core:
https://github.com/rdkcentral/Lightning/pull/451

File: src/Subtitles/index.js [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+    subtitles.fontFamily = v
+  },
+  fontSize(v) {
+    const subtitles = getOrCreateSubtitlesComponent()
+    subtitles.fontSize = v
+  },
+  fontColor(v) {
+    const subtitles = getOrCreateSubtitlesComponent()
+    subtitles.fontColor = v
+  },
```
Comment (ricardo-a-alves-alb) [inline src/Subtitles/index.js:66]: Remains fontColor or is changed to textColor?

File: docs/plugins/subtitles.md [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+Subtitles.fontSize(50)
+```
+
+### fontColor
+
+Sets the `fontColor` style of the Subtitles text
+
+```js
+Subtitles.fontColor(0xffffffff)
+```
```
Comment (ricardo-a-alves-alb) [inline docs/plugins/subtitles.md:88]: If you opt to change this property to textColor, just a reminder to also change the DOCS.

File: docs/plugins/subtitles.md [hunk 8]
```diff
@@ -0,0 +1,144 @@
...
+
+Clears the text of the Subtitles text.
+
+```js
+Subtitles.clear()
+```
+
+### styles
+
+Sets the styles of the Subtitles text. This is a short hand method for setting the following styles: `fontFamily`, `fontSize`, `fontColor`, `backgroundColor`, `textAlign`. If any of these styles are not set, the default values will be used.
```
Comment (ricardo-a-alves-alb) [inline docs/plugins/subtitles.md:55]: Also here.

File: docs/plugins/subtitles.md [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+
+```js
+Subtitles.styles({
+  fontFamily: 'sans-serif',
+  fontSize: 45,
+  fontColor: 0xffffffff,
```
Comment (ricardo-a-alves-alb) [inline docs/plugins/subtitles.md:61]: And also here.

**Review by ricardo-a-alves-alb — CHANGES_REQUESTED** [review]

File: src/Subtitles/SubtitleComponent.js (hunk 3 above)
Comment (michielvandergeest) [reply src/Subtitles/SubtitleComponent.js]: There is no need for the text color to be returned here. It's not relevant in the pre-render calculation of the text texture. We're only interested in the size of the texture and the color doesn't affect that

File: src/Subtitles/SubtitleComponent.js (hunk 4 above)
Comment (michielvandergeest) [reply src/Subtitles/SubtitleComponent.js]: It's actually less CPU intensive to change the color property of the texture versus setting the textColor of the text itself. I don't think there is a real need to change the name of the setter either.

File: src/Subtitles/SubtitleComponent.js (hunk 5 above)
Comment (michielvandergeest) [reply src/Subtitles/SubtitleComponent.js]: Thanks for pointing this out! We indeed have this on our internal backlog to verify with a future release, depending on when / whether PR 451 is merged.

File: docs/plugins/subtitles.md (hunk 7 above)
Comment (uguraslan) [reply docs/plugins/subtitles.md:88]: The same explanation regarding `fontColor` is also valid here : https://github.com/rdkcentral/Lightning-SDK/pull/373#discussion_r1107165496

File: docs/plugins/subtitles.md (hunk 8 above)
Comment (uguraslan) [reply docs/plugins/subtitles.md:55]: The same explanation regarding `fontColor` is also valid here : https://github.com/rdkcentral/Lightning-SDK/pull/373#discussion_r1107165496

File: docs/plugins/subtitles.md (hunk 9 above)
Comment (uguraslan) [reply docs/plugins/subtitles.md:61]: The same explanation regarding `fontColor` is also valid here : https://github.com/rdkcentral/Lightning-SDK/pull/373#discussion_r1107165496

File: src/Subtitles/SubtitleComponent.js (hunk 4 above)
Comment (ricardo-a-alves-alb) [reply src/Subtitles/SubtitleComponent.js:150]: That's actually a great tip that never crossed my mind! 👍

Comment (ricardo-a-alves-alb) [reply src/Subtitles/SubtitleComponent.js:150]: However, with this in mind, should the initial state also use the color and not the textColor property of the texture?

https://github.com/rdkcentral/Lightning-SDK/blob/246e700e4c19c7f0ca1f22fb255df2223fb0d721/src/Subtitles/SubtitleComponent.js#L29-L42

Comment (michielvandergeest) [reply src/Subtitles/SubtitleComponent.js:150]: We could technically omit the initial textColor, since it default to white anyway, but I don't mind having it there for clarity reasons. The technique used (setting the color instead of the textColor) means that we are tinting the text Texture with the color. And since the text itself is white it will result in the exact color that we pass it (tinting a gray text texture would have a different result for example)

**Review by michielvandergeest — APPROVED** [review]
LGTM
